### ISSUE TITLE
cannot load models

### ISSUE THREAD

**Issue by robomano-glitch** [prashant-cn/face-recognition-from-webcam-and-video-sources#1]
I have just cloned the project, initialized npm and installed express and nodemon but when I run the project I get an error in the web console 

```
Uncaught ReferenceError: faceapi is not defined
    <anonymous> http://localhost:3000/js/script.js:4

```

**Comment by prashant-cn** [comment]
@robomano-glitch 
try removing "async" and "defer" from line 26 inside [public/index.tml](https://github.com/prashant-cn/face-recognition-from-webcam-and-video-sources/blob/master/public/index.html)

Let me know if that helps.

**Comment by robomano-glitch** [comment]
Seems to have worked, although now I get another error 
Uncaught (in promise) TypeError: navigator.getUserMedia is not a function
